---
- name: "Create {{ docker_service }} config"
  ansible.builtin.template:
    src: "templates/{{ docker_service }}/{{ docker_service }}.j2"
    dest: "{{ config_path }}/{{ file_name }}"
  tags: never, install, config
  when: docker_service is match("(prowlarr|sonarr|radarr|readarr|lidarr|recyclarr|doplarr)") # services that have config files we generate
