---
- name: "Create {{ docker_service }} docker-compose at {{ docker_compose_path }}"
  ansible.builtin.template:
    src: "templates/{{ docker_service }}/docker-compose.j2"
    dest: "{{ docker_compose_path }}/{{ docker_service }}/docker-compose.yml"
  when: not docker_service is match("(stremio|prowlarr|sonarr|radarr|readarr|lidarr|recyclarr|doplarr)")
  tags: never, install, config
