---
- name: "Standup services"
  include_tasks: standup.yml
  vars:
    docker_service: "{{ item.name }}"
    env_file: "{{ item.env_file }}"
    config_path: "{{ item.config_path }}"
  loop: "{{ services }}"
  when: item.enabled is true
  loop_control:
    loop_var: item
  tags: always, install, config, up, compose
