---
- name: Test docker templates
  hosts: local
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Set docker_compose_path
      set_fact:
        docker_compose_path: "{{ docker_compose_path | default('../examples/docker') }}"
      tags: always, install, config, up, compose
    - name: Include services vars
      include_vars: services.yml
      tags: always, install, config, up, compose

  tasks:
    - name: "Standup services"
      include_role:
        name: docker
      vars:
        docker_service: "{{ item.name }}"
        env_file: "{{ item.env_file }}"
        config_path: "{{ item.config_path }}"
      loop: "{{ services }}"
      when: item.enabled is true
      loop_control:
        loop_var: item
      tags: always, install, config, up, compose
