---
- name: Test docker templates
  hosts: local
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Set docker_compose_path
      set_fact:
        docker_compose_path: "{{ docker_compose_path | default('../examples/docker') }}"
    - name: Include services vars
      include_vars: services.yml

  tasks:
    - name: "Create services docker-compose file"
      ansible.builtin.include_role:
        name: docker
        tasks_from: create-docker-compose
      vars:
        docker_service: "{{ item.name }}"
        env_file: "{{ item.env_file }}"
      loop: "{{ services }}"
      when: item.enabled is true
      loop_control:
        loop_var: item
