---
- name: Docker playbook
  hosts: "{{ docker_host | default('local') }}"
  gather_facts: false

  pre_tasks:
    - name: Set docker_compose_path
      set_fact:
        docker_compose_path: "{{ docker_compose_path | default('../examples/docker') }}"
      tags: always, install, config, up, compose
    - name: Include services vars
      include_vars: services.yml
      tags: always, install, config, up, compose

  roles:
    - role: docker
 